### ISSUE TITLE
PNG error

### ISSUE THREAD

**Issue by billthefreeman** [ppwwyyxx/OpenPano#31]
When running stitching on the taken 72 png pictures by:
./image-stitching 1.png 2.png 3.png 4.png 5.png 6.png 7.png 8.png 9.png 10.png 11.png 12.png 13.png 14.png 15.png 16.png 17.png 18.png 19.png 20.png 21.png 22.png 23.png 24.png 25.png 26.png 27.png 28.png 29.png 30.png 31.png 32.png 33.png 34.png 35.png 36.png 37.png 38.png 39.png 40.png 41.png 42.png 43.png 44.png 45.png 46.png 47.png 48.png 49.png 50.png 51.png 52.png 53.png 54.png 55.png 56.png 57.png 58.png 59.png 60.png 61.png 62.png 63.png 64.png 65.png 66.png 67.png 68.png 69.png 70.png 71.png 72.png
[init_config@main.cc:245] Run with camera estimation mode.

This error message occurs:
error: png encoder error 28: incorrect PNG signature, it's no PNG or corrupted

I wonder if there is a requirement of PNG files.

**Comment by ppwwyyxx** [comment]
I don't know about this because I'm using [lodepng](https://github.com/lvandeve/lodepng) to read the file. You can reproduce the bug with:
```cpp
	vector<unsigned char> img;
	unsigned w, h;
	unsigned error = lodepng::decode(img, w, h, "input.png");
```
and report it in that project.

Alternatively you can remove the if [here](https://github.com/ppwwyyxx/panorama/blob/master/src/lib/imgio.cc#L70) so that it will use CImg to read the png file.

**Comment by billthefreeman** [comment]
It turns out that normal Png files works.
