### ISSUE TITLE
Build issues in VS 2013

### ISSUE THREAD

**Issue by ruizengalways** [ppwwyyxx/OpenPano#32]
I am a beginner in coding. So I just try to write my problems as details as I can. Thanks for your patience.

I installed VS2013 and CMake in my computer and downloaded Eigen3 from the official website. Then I try to build this project with CMake.

![image](https://cloud.githubusercontent.com/assets/9302805/22925675/5cc1e26a-f2f5-11e6-86e2-b091f19caa59.png)
 In README.MD, it is said that '_Set environment variable `EIGEN3_INCLUDE_DIR` so that `${EIGEN3_INCLUDE_DIR}/Eigen/Dense` exists_' But what I can only find is just 'Eigen3_DIR'. Do I need to click 'Add Entry' button to add this variable?

If so, what should I fill in this entry? Actually, I built Eigen3 from the source files downloaded from website. But in the include directory, there is another folder. 
![image](https://cloud.githubusercontent.com/assets/9302805/22926176/3c5fcef4-f2f7-11e6-87d2-0c7926595589.png)
The *.h files seems in below files
![image](https://cloud.githubusercontent.com/assets/9302805/22926203/51e9ea34-f2f7-11e6-86cc-68c759c2617b.png)
So what directory I should add?

My second question is that how to add jpeg support to this project. Just click 'Add Entry' to add JPEG_INCLUDE_DIR and JPEG_LIBRARY? or e.g. C:\jpeg-9a\jpeg.lib

My third question is If I use this, how can I cite this work. Just cite the this website?
Thanks again.

**Comment by ppwwyyxx** [comment]
First of all I don't know how to build it on windows. The cmake was contributed by others. I'll provide my best guess based on how cmake works.
1. You'll need to add an entry EIGEN3_INCLUDE_DIR
2. You should fill the value to this variable such that ${EIGEN3_INCLUDE_DIR}/Eigen/Dense exists. If you download eigen from [the official website](http://eigen.tuxfamily.org/index.php?title=Main_Page), you can see the file `Eigen/Dense` outside the `src` directory.

The CMakeLists.txt had some bugs with jpeg. I pushed a fix just now, but I still don't know does it work for windows or not. If it doesn't work automatically, you're supposed to do the following:
1. set JPEG_INCLUDE_DIR so that ${JPEG_INCLUDE_DIR}/jpeglib.h exists.
2. set JPEG_LIBRARY so that ${JPEG_LIBRARY}/jpeg.lib exists. In fact I don't know if it should be called jpeg.lib on windows.. I assume it is since you have that file.

You can just cite the github page with the name OpenPano.

**Comment by ruizengalways** [comment]
Actually I tried what you said just. I added 'EIGEN3_INCLUDE_DIR', 'JPEG_INCLUDE_DIR' and 'JPEG_LIBRARY'.

I got errors in visual studio. May be I need to compile this in Linux. 
![image](https://cloud.githubusercontent.com/assets/9302805/22927965/abbd2ab4-f2ff-11e6-8214-d64cde495066.png)

By the way, what you wrote in your blog is very nice for beginner in image stitching. Thanks for sharing

**Comment by ruizengalways** [comment]
我艹，突然发现竟然是知乎大神吴育昕的github，膜拜下。。。。。。

**Comment by ppwwyyxx** [comment]
The README says you'll need vs2015. Some of the errors indicate that vs2013 lacks necessary C++ language features.
