### ISSUE TITLE
Compile issues in vs 2015

### ISSUE THREAD

**Issue by hust0zzcc** [ppwwyyxx/OpenPano#36]
Thanks for sharing,but there are some errors when I compile your project in vs 2015.I appreciate you a lot if you can do me a favor!

**Comment by ppwwyyxx** [comment]
Please report your issue.
Disclaimer: I never compiled it under windows but a lot of users reported successful compilation.

**Comment by hust0zzcc** [comment]
Thank you very much for your reply!
I'm sorry I don't know how to upload pictures in GitHub.I will try to compile again in our group's computer.Maybe there are some problems in my vs 2015 settings.

**Comment by hust0zzcc** [comment]
![image](https://cloud.githubusercontent.com/assets/26895204/24685559/f64b7d62-19e0-11e7-9f60-7690591ed61d.png)
This is part of my error when compiling

**Comment by ppwwyyxx** [comment]
I cannot help you debug the problem since I don't have windows. But in the
PR of windows build, there is a file added specifically for your problem:
https://github.com/ppwwyyxx/OpenPano/pull/26/files#diff-6db14502cb95ebeea4a63d2129c7515b

You can take a look why ``#define not !`` is not working for you.
