### ISSUE TITLE
CMake compilation error on Windows 10

### ISSUE THREAD

**Issue by ashwin4ever** [ppwwyyxx/OpenPano#55]
I am facing a CMake compilation error. I am having Windows 10 with Visual Studio 2013.

The error message is 

> Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
-- Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
EIGEN3_INCLUDE_DIR
   used as include directory in directory C:/Users/akanna/Desktop/Image Stiching/OpenPano-master/src
   used as include directory in directory C:/Users/akanna/Desktop/Image Stiching/OpenPano-master/src
   used as include directory in directory C:/Users/akanna/Desktop/Image Stiching/OpenPano-master/src/third-party
-- Configuring incomplete, errors occurred!

Could you help me out

**Comment by FinleyPan** [comment]
First, make sure you not missing Eigen3, and there may be a bug in cmake configuration because the libjpeg is optional. Following is my solution, download and compile [libjpeg-turbo](https://github.com/libjpeg-turbo/libjpeg-turbo)(may also need [nasm](http://www.nasm.us/) to build libjpeg in Windows) then remove all the statements about Eigen and libjpeg in CMakeLists.txt in src. Now  the solution should be generated successfully,modify project properties(set Include_directories library_directories and linker to Eigen and libjpeg ) before building the solution. Besides you may need do some mild adjustments in the code(VS doesn't support some statements in the source code, I think author compiled this project in other platform ), you can follow hints of compiler to adjust. Ok that is all, good luck to you!
